[BUG] fix the download and upload path
DinoHub/dinohub.github.io pull request #4
Opened 2020-12-04 08:35 UTC by jinmingteo

Edit download and upload directory in the example

2020-12-05 15:13 UTC, jax79sg requested changes
Hi Jinming, sorry, looking at this again. I don't think the change should be like this. I do however agree that the original code is ambiguous as well. So basically if we change the code to this, we are assuming we are download the S3 file and saving it as the same filename. However, people can choose to save as a different path and filename. So i recomend changing names only instead.

`s3path` change to `s3pathandfilename`
`localfile` change to `localpathandfilename`

2020-12-05 15:13 UTC, jax79sg commented on _posts/2020-07-13-ml-dl-model-training-on-aiplatform-part1.md
> +    s3.Bucket(bucket).download_file(os.path.join(s3path, localfile), localfile)
Hi Jinming, sorry, looking at this again. I don't think the change should be like this. I do however agree that the original code is ambiguous as well. So basically if we change the code to this, we are assuming we are download the S3 file and saving it as the same filename. However, people can choose to save as a different path and filename. So i recomend changing names only instead.

s3path change to s3pathandfilename
localfile change to localpathandfilename

2020-12-07 03:48 UTC, jinmingteo commented on _posts/2020-07-13-ml-dl-model-training-on-aiplatform-part1.md
> +    s3.Bucket(bucket).download_file(os.path.join(s3path, localfile), localfile)
Hi Kah Siong,

agreed with your changes. I guess the part i was confused about was the subdirectory that we needed in order to reach the s3 files. (for example, digitalhub/**cat_dog**/kagglecatsanddogs_3367a.zip).

Hopefully this commit will clear the confusion. Maybe we will have to edit this page too
https://raw.githubusercontent.com/jax79sg/kubejob/master/single-train/image_classification_single.py

2020-12-07 04:46 UTC, jax79sg approved these changes
Thanks a lot. @jinmingteo

2020-12-08 05:53 UTC, merged